package techguns.core;

import java.util.List;

/** Generated from the selected original workbench recipe graph. */
public final class CraftingContent {
    public static final List<String> MATERIALS = List.of("advancedrounds", "antigravcore", "biomass", "carbonfibers", "circuitboard", "circuitboardelite", "coil", "copperwire", "cyberneticparts", "electricengine", "enricheduranium", "goldwire", "infusionbag", "ingotbronze", "ingotcopper", "ingotlead", "ingotobsidiansteel", "ingotsteel", "ingottin", "ingottitanium", "ironbarrel", "ironreceiver", "laserfocus", "machinestackupgrade", "mechanicalpartscarbon", "mechanicalpartsiron", "mechanicalpartsobsidiansteel", "nuggetcopper", "nuggetlead", "nuggetsteel", "obsidiansteelbarrel", "obsidiansteelreceiver", "oretitanium", "plasticsheet", "plasticstock", "platebronze", "platecarbon", "platecopper", "plateiron", "platelead", "plateobsidiansteel", "platesteel", "platetin", "platetitanium", "powerplating", "quartzrod", "radaway", "rademitter", "radpills", "rawplastic", "rawrubber", "rcheatray", "rcuvemitter", "rubberbar", "sonicemitter", "steamarmorplate", "steelreceiver", "stonebarrel", "tgx", "treatedleather", "turretarmoriron", "turretarmorobsidiansteel", "turretarmorsteel", "woodstock", "yellowcake");
    public static final List<String> EXTRA_AMMO = List.of("40mmgrenade", "biotank", "biotankempty", "compressedairtank", "compressedairtankempty", "energycellempty", "fueltank", "fueltankempty", "gaussrifleslugs", "nethercharge", "nuclearpowercell", "nuclearpowercelldepleted", "pistolrounds_incendiary", "riflerounds_incendiary", "rifleroundsstack", "rifleroundsstack_incendiary", "rocket", "rocket_high_velocity", "shotgunrounds_incendiary", "sniperrounds_explosive", "sniperrounds_incendiary");
    public static final List<String> RECIPE_IDS = List.of("ak47", "ak47_alt", "as50", "as50_alt", "aug", "aug_alt", "ammo_press", "metal_press", "metal_press_alt", "chem_lab", "boltaction", "combatshotgun", "goldenrevolver", "handcannon", "stonebullets", "turretarmorsteel", "turretarmorobsidiansteel", "quartzrod", "quartzrod_alt", "rcheatray", "smgmagazineempty", "riflerounds_incendiary", "rifleroundsstack_incendiary", "pistolmagazine", "pistolmagazineempty", "assaultriflemagazine", "infusionbag", "assaultriflemagazineempty", "lmgmagazine", "lmgmagazine_alt", "lmgmagazineempty", "as50magazine", "pistolrounds", "as50magazineempty", "compressedairtankempty", "compressedairtankempty_alt", "biotankempty", "fueltankempty", "shotgunrounds", "ironreceiver", "steelreceiver", "obsidiansteelreceiver", "stonebarrel", "ironbarrel", "obsidiansteelbarrel", "riflerounds", "woodstock", "plasticstock", "mechanicalpartsiron", "biomass", "copperwire", "circuitboard", "circuitboardelite", "coil", "electricengine", "ingotcopper", "rocket", "ingotlead", "ingotsteel", "nuggetcopper", "nuggetlead", "nuggetsteel", "rifleroundsstack", "machinestackupgrade", "turretarmoriron", "smgmagazine", "lmg", "lmg_alt", "m4", "m4_alt", "mac10", "mac10_alt", "fabricator_housing", "fabricator_glass", "fabricator_controller", "reactionchamber_housing", "reactionchamber_glass", "reactionchamber_controller", "pistol", "pistol_alt", "revolver", "sawedoff", "scar", "scar_alt", "blast_furnace", "thompson", "thompson_alt", "vector", "vector_alt");
    private CraftingContent() {}
}
